name: CD Pipeline

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug SSH Setup
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 Host to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.AWS_PUBLIC_IP }} >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -o StrictHostKeyChecking=accept-new -i ~/.ssh/id_rsa ${{secrets.AWS_USER}}@${{ secrets.AWS_PUBLIC_IP }} "cd /home/ubuntu/fastapi-book-project && git pull origin main && sudo systemctl restart fastapi.service"
